### ISSUE TITLE
panic: invalid argument to Intn

### ISSUE THREAD

**Issue by ghost** [MaxHalford/pointu#1]
```
$ convert -size 100x100 xc:black black.png
$ pointu -in black.png -out black_p.png
panic: invalid argument to Intn

goroutine 1 [running]:
math/rand.(*Rand).Intn(0xc4200182d0, 0x0, 0xc42003fbbc)
        /home/user/go/src/math/rand/rand.go:141 +0xc7
github.com/MaxHalford/pointu/pointu.ImportanceSample(0x1f4, 0xc4200143c0, 0xc4200143c8, 0xc4200182d0, 0x64, 0x0, 0xc420014140)
        /home/user/gocode/src/github.com/MaxHalford/pointu/pointu/importance_sampling.go:35 +0x336
main.main()
        /home/user/gocode/src/github.com/MaxHalford/pointu/cli.go:55 +0x13a
```

**Comment by MaxHalford** [comment]
Fixed, the problem happened when there were no points for a given threshold - in your case most of the whiter values.
